# This workflow runs every weekday at 15:00 UTC (8AM PDT)
name: Daily CI

on:
  schedule:
    - cron: "00 15 * * 1-5"

jobs:
  daily-ci-net:
    if: github.event_name != 'schedule' || github.repository_owner == 'aws'
    uses: ./.github/workflows/library_net_tests.yml
    with:
      dafny: '4.1.0'
