# This workflow runs for every push to main
name: Push CI

on:
  push:
    branches:
      - main    

jobs:
  push-ci-net:
    uses: ./.github/workflows/library_net_tests.yml
    with:
      dafny: '4.1.0'
